<a href="https://colab.research.google.com/github/LKVan/Lab2_ML/blob/van/Lab1_20130462_LeKhanhVan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from IPython.core.display import Math
import datetime as date
from abc import ABC, abstractmethod
import numpy as np

Task1.1

In [ ]:
n = int(input("n = "))
i = 0
L = list()
for i in range(n):
  L.append(int(input(str(i)+ "=")))
print(L)
print(max(L))
print(min(L))
sum = 0
for i in L:
  sum = sum + i
print(sum)
L.sort()
print(L)
positive = 0
nagative = 0
for j in L:
  if j < 0:
    nagative = nagative +1
  elif j > 0:
    positive = positive + 1
print("so so duong = " + str(positive))
print("so so am = " + str(nagative))

n = 4
0=1
1=5
2=3
3=10
[1, 5, 3, 10]
10
1
19
[1, 3, 5, 10]
so so duong = 4
so so am = 0


Task1.2

In [ ]:
def sn(n):
  sn = 0
  for i in range(n):
    sn += 1/(2*i+1)
  print(sn)
sn(int(input("n = ")))

n = 5
1.7873015873015872


Task1.3

In [ ]:
class Product(ABC):
  def __init__(self, name, kind ,price, expiredDate):
    self._name = name
    self._kind = kind
    self._price = price
class ImportedProduct(Product):
  def __init__(self,name, kind ,price, expiredDate, fromCountry):
    super().__init__(name, kind ,price, expiredDate)
    self._fromCountry = fromCountry
class DomesticProduct(Product):
  def __init__(self,name, kind ,price, expiredDate):
    super().__init__(name, kind ,price, expiredDate)
class OderItem:
  def __init__(self, item, amount):
    self.item = item
    self.amount = amount
class Oder:
  def __init__(self, id, customer, employee, date, items):
    self.id = id
    self.customer = customer
    self.employee = employee
    self.date = date
    self.items = items
class OderMananger:
  def __init__(self,oders):
    self.oders = oders
  def _highestPrice(self):
    max = 0
    for oder in self.oders:
      for item in oder.items:
        if item.item._price > max:
          max = item.item._price
    return max
  def _numProductBoughtByType(self,kind):
    count = 0
    for oder in self.oders:
      for item in oder.items:
        if item.item._kind == kind:
          count+= item.amount
    return count
p1 = ImportedProduct('ca phe', 'den', 10000, date.date(2023,5,20),'America')
p2 = ImportedProduct('ca phe', 'sua', 20000, date.date(2023,5,19), 'China')
p3 = DomesticProduct('tra', 'dao', 25000, date.date(2023,5,20))
p4 = DomesticProduct('tra', 'tac', 20000, date.date(2023,5,19))
odi1 = OderItem(p1, 2)
odi2 = OderItem(p2, 3)
odi3 = OderItem(p3, 1)
odi4 = OderItem(p4, 4)
list1 = [odi1, odi2]
list2 = [odi3, odi4]
od1 = Oder('kh1','Le Khanh Van', 'Nguyen Van A', date.date(2023, 2, 20), list1)
od2 = Oder('kh2','Le Khanh Gun', 'Nguyen Van B', date.date(2023, 2, 19), list2)
listoder = [od1, od2]
oderManger = OderMananger(listoder)
print(oderManger._highestPrice())
print(oderManger._numProductBoughtByType('den'))
print(p1._fromCountry)

25000
2
America


Task2.1

In [ ]:

arr = np.arange(10,26)
arr2 = arr[::-1]
print(arr2)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task2.2

In [ ]:
def _repeat(array):
  n = int(input("n = "))
  arr1 = np.copy(array)
  for i in range(n-1):
    arr2 = np.copy(arr1)
    array = np.concatenate((array,arr2),axis = 0)
  return array
print(_repeat(np.array([1,2,3,4])))

n = 3
[1 2 3 4 1 2 3 4 1 2 3 4]


Task2.3

In [ ]:
def replace(list):
  for i in range(len(list)):
    for j in range(len(list[i])):
      if list[i,j] > 0.5:
        list[i,j] = 0.5
  print(list)
list = np.array([[ 0.42, 0.48, 0.32],
[ 0.74, 0.58, 0.38],
[ 0.51, 0.34, 0.15 ]])
replace(list)

[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
